### ISSUE TITLE
SPERR does not build with OpenMP on macOS

### ISSUE THREAD

**Issue by lindstro** [NCAR/SPERR#186]
**Describe the bug**
Building SPERR with Apple clang on macOS results in this compiler warning and no OpenMP support:
```
clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
```

**To Reproduce**
1. `mkdir build`
2. `cd build`
3. `cmake ..`
4. `make`

**Expected and actual behavior**
The build works when commenting out this line in `src/CMakeLists.txt`:
```
  target_compile_options(   SPERR PUBLIC ${OpenMP_CXX_FLAGS} )
```
This line appears unnecessary for Linux builds.

**Environment (please complete the following information):**
 - OS: macOS 11.7.2
 - Compiler: AppleClang 13.0.0.13000029
 - SPERR Version: 0.6 (and earlier versions)

**Comment by shaomeng** [comment]
Apple supplied toolchain has a weird relationship with OpenMP, but it does look like that CMakeLists.txt line doesn't help anything except than introducing a warning. I've removed that command; thanks for finding out the offending line Peter!
