### ISSUE TITLE
Where did all the symbols go?

### ISSUE THREAD

**Issue by robertu94** [NCAR/SPERR#221]
**Describe the bug**
When I attempt to build SPERR version 0.7.1, I get a linking error whenever I attempt to link to it.  It looks like the symbols are missing.

**To Reproduce**

```
mkdir build
cd build
cmake ..
cmake --build .
cmake --install

# build and attempt to link to libpressio-sperr
```

**Expected and actual behavior**
```
❯ objdump -t ./build/src/libSPERR.so.0.7.1  |grep sperr_decomp_2d

```

This should return at least one line with this symbol...

```
SPERR (c2cd092) via △ v3.27.7 
❯ git log -n 1 --format=oneline
c2cd092f2b55136bb246a680ea3406db8b71f99f (HEAD, tag: v0.7.1, origin/main, origin-main) bump version number to 0.7.1
```

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Compiler GCC 13.1
 - SPERR Version

**Comment by shaomeng** [comment]
I cannot reproduce it on an ubuntu box and I don't have access to a Fedora box. This is a very odd symptom; do you mind clean up everything and try again? 
 
<img width="703" alt="Screenshot 2023-10-24 at 3 13 12 PM" src="https://github.com/NCAR/SPERR/assets/814885/0137919b-d8c7-4c78-922e-2febe269bbf6">

**Comment by robertu94** [comment]
@shaomeng sorry for the noise.  This seems to be an issue with a stale `ccache` that I didn't realize was being used by default.
