### ISSUE TITLE
Fortran Wrappers for SPERR

### ISSUE THREAD

**Issue by ofmla** [NCAR/SPERR#237]
I have recently created Fortran wrappers for SPERR, aiming to extend its accessibility to users who primarily work in Fortran. These wrappers provide seamless integration with Fortran programs, allowing users to leverage the functionality of SPERR within their Fortran projects. I've developed a CI workflow that tests the wrappers by running a couple of C examples and comparing the outputs with their Fortran counterparts to ensure consistency. While this isn't a formal issue, I wanted to notify you of this development and kindly request to include a link to the Fortran wrappers in the README of the official SPERR repository. This would make it easier for users to discover and utilize these wrappers, thus improving the overall usability of SPERR.

Wrapper Link: https://github.com/ofmla/fortran-sperr

If you require any further information or assistance regarding the wrappers or their integration, please don't hesitate to reach out. Thank you for considering this request, and I look forward to seeing the Fortran wrappers linked in the README.

Best regards,
Oscar

**Comment by shaomeng** [comment]
Hi @ofmla , this looks awesome! Do you mind letting me know a bit more about the work you're doing and if/how SPERR is used? 

I'm on travel this week, so I'll look at the wrapper closely and hopefully to link it next week!

**Comment by ofmla** [comment]
I was working with compression to accelerate adjoint-based optimization problem in my field (geosciences/geophysics). I wanted to test other alternatives to the classic ZFP, SZ3, etc ;)

**Comment by shaomeng** [comment]
Hi @ofmla , it sounds like a cool use of SPERR; please let me know if you have any question or interesting discoveries about SPERR.

I've also added the link at the README file. Please see if it's what you expected. Thanks!

**Comment by ofmla** [comment]
Thanks, it's just like that. I hope the wrappers will be useful for someone.
